//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinecraftEnchantCalculator.Resources.Settings {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.9.0.0")]
    internal sealed partial class LanguageKey : global::System.Configuration.ApplicationSettingsBase {
        
        private static LanguageKey defaultInstance = ((LanguageKey)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new LanguageKey())));
        
        public static LanguageKey Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EnchantedBook")]
        public string EnchantedBook {
            get {
                return ((string)(this["EnchantedBook"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FeasibleYes")]
        public string FeasibleYes {
            get {
                return ((string)(this["FeasibleYes"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FeasibleNo")]
        public string FeasibleNo {
            get {
                return ((string)(this["FeasibleNo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Welcome")]
        public string Welcome {
            get {
                return ((string)(this["Welcome"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CalculatePressed")]
        public string CalculatePressed {
            get {
                return ((string)(this["CalculatePressed"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AddFavoriteSuccess")]
        public string AddFavoriteSuccess {
            get {
                return ((string)(this["AddFavoriteSuccess"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FavoriteNameDiscard")]
        public string FavoriteNameDiscard {
            get {
                return ((string)(this["FavoriteNameDiscard"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FavoriteNameInputClosed")]
        public string FavoriteNameInputClosed {
            get {
                return ((string)(this["FavoriteNameInputClosed"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DeleteFavoriteFailed")]
        public string DeleteFavoriteFailed {
            get {
                return ((string)(this["DeleteFavoriteFailed"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DeleteFavoriteSuccess")]
        public string DeleteFavoriteSuccess {
            get {
                return ((string)(this["DeleteFavoriteSuccess"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FavoriteSelectChanged")]
        public string FavoriteSelectChanged {
            get {
                return ((string)(this["FavoriteSelectChanged"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AddFavoriteFailed")]
        public string AddFavoriteFailed {
            get {
                return ((string)(this["AddFavoriteFailed"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LoadFavoriteFailed")]
        public string LoadFavoriteFailed {
            get {
                return ((string)(this["LoadFavoriteFailed"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FavoriteHasPresent")]
        public string FavoriteHasPresent {
            get {
                return ((string)(this["FavoriteHasPresent"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LoadFavoriteSuccess")]
        public string LoadFavoriteSuccess {
            get {
                return ((string)(this["LoadFavoriteSuccess"]));
            }
        }
    }
}
